create table tb_address (address_id int8 generated by default as identity, city varchar(255), number varchar(255), state varchar(255), street varchar(255), worker_id int8, primary key (address_id));
create table tb_worker (worker_id int8 generated by default as identity, daily_income float8, name varchar(255), primary key (worker_id));
alter table if exists tb_address add constraint FKmyx0985hyuscgkh3ldvuuhnwv foreign key (worker_id) references tb_worker;
create table tb_role (role_id int8 generated by default as identity, role_name varchar(255), primary key (role_id));
create table tb_user (user_id int8 generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (user_id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table if exists tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
alter table if exists tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table if exists tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
