create table tb_address (address_id int8 generated by default as identity, city varchar(255), number varchar(255), state varchar(255), street varchar(255), worker_id int8, primary key (address_id));
create table tb_worker (worker_id int8 generated by default as identity, daily_income float8, name varchar(255), primary key (worker_id));
alter table if exists tb_address add constraint FKmyx0985hyuscgkh3ldvuuhnwv foreign key (worker_id) references tb_worker;
